[book]
title = "Notes"
authors = ["Clay Dunston"]
src = "src"
multilingual = false
# additional-js = ["custom.js"]
# additional-css = ["custom.css", "custom2.css"]

[build]
build-dir = "docs"
create-missing = false
